<!-- Footer -->
<section id="footer" class="column">
    <div class="row">
        <div class="map"><img src="images/map.png" alt="map-image" width="100%" /></div>
        <div>
            <h2>Vancouver Aquarium</h2>
            <div><span class="strong">Phone</span>+1 (234) 456-7890</div>
            <div><span class="strong">Address</span>845 Avision Way, Vancouver, BC V6G 3E2</div>
            <div class="row">
                <div class="menu">
                    <h4>Menu</h4>
                    <li><a href="#home">Home</a></li>
                    <li><a href="#visit">Visit</a></li>
                    <li><a href="#explore">Explore</a></li>
                    <li><a href="#contact">Contact</a></li>
                </div>
                <div class="support">
                    <h4>Support</h4>
                    <li><a>Lorem ipsum</a></li>
                    <li><a>Lorem ipsum</a></li>
                    <li><a>Lorem ipsum</a></li>
                    <li><a>Lorem ipsum</a></li>
                </div>
                <div class="socials">
                    <h4>Socials</h4>
                    <div class="social-icons"></div>
                        <li><i class="far fa-envelope fa-1x"></i></li>
                        <li><i class="fab fa-facebook-f fa-1x"></i></li>
                        <li><i class="fab fa-instagram fa-1x"></i></li>
                        <li><i class="fab fa-twitter fa-1x"></i></li>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright">2020 © designed and developed by Irene Kwon</div>
</section>