<!-- Home -->
<section id="home" class="column">
    <!-- Slider -->
    <input checked id="slide-1" name="active" type="radio" />
    <div class="slide">
        <h1>Vancouver Aquarium</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
        <div class="learn-more">Learn More</div>
    </div>
    <nav class="arrows">
        <label class="prev" for="slide-3">
            <i class="fas fa-chevron-left fa-2x"></i>
        </label>
        <label class='next' for='slide-2'>
            <i class="fas fa-chevron-right fa-2x"></i>
            </label>
    </nav>

    <input id="slide-2" name="active" type="radio" />
    <div class='slide'>
        <h1>Vancouver Aquarium</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
        <div class="learn-more">Learn More</div>
    </div>
    <nav class="arrows">
        <label class='prev' for='slide-1'>
            <i class="fas fa-chevron-left fa-2x"></i>
        </label>
        <label class='next' for='slide-3'>
            <i class="fas fa-chevron-right fa-2x"></i>
            </label>
    </nav>

    <input id="slide-3" name="active" type="radio" />
    <div class='slide'>
        <h1>Vancouver Aquarium</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit</p>
        <div class="learn-more">Learn More</div>
    </div>
    <nav class="arrows">
        <label class='prev' for='slide-2'>
            <i class="fas fa-chevron-left fa-2x"></i>
        </label>
        <label class='next' for='slide-1'>
            <i class="fas fa-chevron-right fa-2x"></i>
            </label>
    </nav>
</section>