<!-- Navbar -->
<nav id="navbar">
    <div class="logo">
        <a href="#home">Vancouver Aquarium</a>
    </div>
    <div class="navbar-content row">
        <ul class="row">
            <li><a href="#home">Home</a></li>
            <li><a href="#visit">Visit</a></li>
            <li><a href="#explore">Explore</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
        <div class="social-icons row">
            <li><i class="far fa-envelope fa-1x"></i></li>
            <li><i class="fab fa-facebook-f fa-1x"></i></li>
            <li><i class="fab fa-instagram fa-1x"></i></li>
            <li><i class="fab fa-twitter fa-1x"></i></li>
        </div>
    </div>
</nav>