<!-- Visit -->
<section id="visit" class="column">
    <div class="visit-heading">Visit</div>
    <div class="visit-desc">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Facilis corrupti possimus cupiditate ratione ipsam consequuntur sint vitae? Optio molestias, 
        earum similique, cum neque, aut quibusdam rerum cupiditate dolorum corrupti atque!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        Facilis corrupti possimus cupiditate ratione ipsam consequuntur sint vitae? Optio molestias, 
        earum similique, cum neque, aut quibusdam rerum cupiditate dolorum corrupti atque!
    </div>
</section>